<?php

namespace Database\Seeders;

use App\Models\Document;
use App\Models\Project;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;

class DocumentSeeder extends Seeder
{
    public function run(): void
    {
        $projects = Project::all();
        foreach ($projects as $project) {
            if ($project->documents()->count() > 0) {
                continue;
            }
            $dir = 'project-documents/' . $project->id;
            Storage::makeDirectory($dir);
            $path = $dir . '/sample-spec.txt';
            Storage::put($path, 'Sample specification document for ' . $project->project_name . "\nGenerated by seeder.");
            Document::create([
                'project_id' => $project->id,
                'title' => 'Sample spec',
                'file_path' => $path,
                'uploaded_at' => now(),
            ]);
        }
    }
}
